@startmindmap

+ Intro
++ Who you are? 
+++ The Solution Architect who strong at Microservices, Cloud Native and AWS 
+++ having AWS Solution Architect Professional ceritificate
+++ the leader who has experience to manage team 17 members include 10 developers
+++ a ex-prdcv employee, who looking forward to have a chance to comeback 
++ Why you leave from PRDCV?
+++ hungry of working a large development team and Microservices 
++ What you archive on Nashtech?
+++ having strong experience with Cloud Native  and Microservices architecture
+++ Design, implement and golive 2 Microservices system, 
+++ continous develop the Production with Roadmap and lifecycle
+++ Manage a large team having 17 members include 10 developers 
+++ mentor developers by daily tasks and knowhow sharing 
+++ having AWS Solution Architect Professional ceritificate
-- Why you comeback? 
--- Promise for comming back when leaving
--- target to become a Enterprise Architect who able to handle big picture of Organization 
--- PRDCV is the best environment for people development 
--- PRDCV is now becoming a Panasonic Cloud Center with many challenge of providing Cloud solution in Organization level
--- PRDCV will be my next step for my career on longterm 5-10 years 
-- Why you leave from Nashtech now?
--- The project is completed
--- contract with Nashtech will be end soon 
--- right time to have next step for career path

@endmindmap 